name: Docker Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t frontend-test .

      - name: Run Docker container
        run: docker run -d --name frontend-container -p 8080:80 frontend-test

      - name: Wait for container to start
        run: sleep 10

      - name: Test application
        run: |
          curl -f http://localhost:8080 || exit 1
          echo "Application is running successfully"
          //app 

      - name: Stop and remove container
        run: docker stop frontend-container && docker rm frontend-container
